Repository gabdiniz/soulpet_front, pull requests merged in 2023-05, with the labels that each got.

#45 Adicionado o filtro de pesquisa de produtos
  src/pages/Produtos/Produtos.jsx
Labels: bug, documentation, enhancement

#48 Loc ibge
  src/pages/EditaCliente/EditaCliente.jsx
  src/pages/NovoCliente/NovoCliente.jsx
Labels: documentation, enhancement

#50 Integrar a inserção de Agendamentos
  src/App.js
  src/pages/NovoAgendamento/NovoAgendamento.jsx
Labels: documentation, enhancement

#52 Integrar a listagem de Agendamentos
  src/App.js
  src/components/Header/Header.jsx
  src/pages/Agendamentos/Agendamentos.jsx
Labels: documentation, enhancement

#53 Integrar a remoção de Agendamentos
  src/pages/Agendamentos/Agendamentos.jsx
Labels: documentation, enhancement

#54 Integrar a atualização de pedidos
  src/App.js
  src/pages/EditarPedido/EditarPedido.jsx
Labels: documentation

#58 Implementar paginação de Pets
  src/pages/Pets/Pets.jsx
Labels: documentation

#59 Integrar a atualização de Agendamentos
  src/App.js
  src/pages/Agendamentos/Agendamentos.jsx
  src/pages/EditaAgendamento/EditaAgendamento.jsx
Labels: documentation, enhancement

#60 [SPT-9] Implementar uma tela de Dashboard do Sistema
  src/App.js
  src/components/Header/Header.jsx
  src/components/Header/style.css
  src/index.js
  src/pages/Agendamentos/Agendamentos.jsx
  src/pages/Clientes/Clientes.jsx
  src/pages/Dashboard/Dashboard.jsx
  src/pages/Dashboard/style.css
  src/pages/DetalhesCliente/DetalheCliente.jsx
  src/pages/NovoAgendamento/NovoAgendamento.jsx
  src/pages/Pedidos/Pedidos.jsx
  src/pages/Pets/Pets.jsx
  src/pages/Produtos/Produtos.jsx
  src/pages/Root/Root.jsx
Labels: documentation, enhancement

#63 Criar documentação para os repositórios de front-end e back-end em ma…
  LICENSE.md
  README.md
Labels: documentation, enhancement
